#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Audit a staged Windows package for missing runtime dependencies.

`craft --package` succeeds whether or not the package is complete, and the
build machine has Visual Studio and the KDE stack installed, so an incomplete
package still runs there. This checks two things the packaging step does not:

1. Every DLL imported by a packaged binary is either in the package or
   provided by Windows.
2. The data files the application resolves at runtime are present.

Usage:
    check-windows-deps.py <package-root> [--allow name.dll ...] [--no-payload]
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

# DLLs Windows provides, so importing them without shipping them is fine.
# The Visual C++ redistributable (vcruntime140*.dll, msvcp140*.dll,
# concrt140.dll, vccorlib140.dll, mfc140*.dll) is deliberately not listed: it
# is not part of Windows and has to be shipped.
SYSTEM_DLLS = {
    "activeds.dll", "advapi32.dll", "authz.dll", "avicap32.dll", "avrt.dll",
    "bcrypt.dll", "bcryptprimitives.dll", "bluetoothapis.dll",
    "cabinet.dll", "cfgmgr32.dll", "clbcatq.dll", "combase.dll",
    "comctl32.dll", "comdlg32.dll", "coml2.dll", "credui.dll",
    "crypt32.dll", "cryptbase.dll", "cryptui.dll", "d2d1.dll", "d3d10.dll",
    "d3d11.dll", "d3d12.dll", "d3d9.dll", "d3dcompiler_47.dll",
    "dbghelp.dll", "dcomp.dll", "devobj.dll", "dinput8.dll", "dnsapi.dll",
    "dsound.dll", "dwmapi.dll", "dwrite.dll", "dxgi.dll", "dxva2.dll",
    "faultrep.dll", "feclient.dll", "firewallapi.dll", "fwpuclnt.dll",
    "gdi32.dll", "gdi32full.dll", "gdiplus.dll", "glu32.dll", "hid.dll",
    "httpapi.dll", "icu.dll", "imm32.dll", "iphlpapi.dll", "kernel32.dll",
    "kernelbase.dll", "ksuser.dll", "ktmw32.dll", "mf.dll", "mfplat.dll",
    "mfreadwrite.dll", "mfuuid.dll", "mpr.dll", "msacm32.dll",
    "mscoree.dll", "msctf.dll", "msdmo.dll", "msi.dll", "msimg32.dll",
    "msvcrt.dll", "mswsock.dll", "ncrypt.dll", "netapi32.dll",
    "normaliz.dll", "ntdll.dll", "odbc32.dll", "ole32.dll", "oleacc.dll",
    "oleaut32.dll", "oledlg.dll", "opengl32.dll", "pdh.dll", "powrprof.dll",
    "profapi.dll", "propsys.dll", "psapi.dll", "rpcrt4.dll", "rstrtmgr.dll",
    "sechost.dll", "secur32.dll", "setupapi.dll", "shcore.dll",
    "shell32.dll", "shlwapi.dll", "sspicli.dll", "tdh.dll", "ucrtbase.dll",
    "uiautomationcore.dll", "urlmon.dll", "user32.dll", "userenv.dll",
    "usp10.dll", "uxtheme.dll", "version.dll", "wer.dll", "wevtapi.dll",
    "win32u.dll", "windowscodecs.dll", "winhttp.dll", "wininet.dll",
    "winmm.dll", "winspool.drv", "wintrust.dll", "winusb.dll",
    "wldap32.dll", "ws2_32.dll", "wsock32.dll", "wtsapi32.dll",
    "xinput1_3.dll", "xinput1_4.dll",
}

# Virtualised API sets and OS component DLLs, matched by prefix.
SYSTEM_PREFIXES = ("api-ms-win-", "ext-ms-win-", "windows.", "microsoft.windows.")

# Data files the app resolves at runtime, relative to the package root, with
# `*` matching one path segment. The second element names the consumer.
EXPECTED_PAYLOAD = [
    ("bin/fontmatrix.exe", "the application itself"),
    ("bin/data/kxmlgui5/fontmatrix/fontmatrixui.rc",
     "KXmlGui menu bar and toolbar definition"),
    ("bin/data/icons/hicolor/48x48/apps/fontmatrix.png",
     "window/taskbar icon via QIcon::fromTheme()"),
    ("bin/data/icons/hicolor/22x22/status/fontmatrix-tray.png",
     "KStatusNotifierItem tray icon"),
    ("bin/data/fontmatrix/resources/template_default.xml",
     "Font Book default template"),
    ("bin/data/fontmatrix/resources/Samples/*/*",
     "per-script text samples"),
    ("bin/data/locale/*/LC_MESSAGES/fontmatrix.mo",
     "translations (KLocalizedString catalogues)"),
    ("bin/data/fontmatrix/handbook/en/index.html",
     "the handbook FMHandbookWindow shows on F1 (generated by kdoctools)"),
]


class PEError(Exception):
    pass


def _cstr(blob: bytes, offset: int) -> str:
    end = blob.find(b"\0", offset)
    if end < 0:
        raise PEError("unterminated string")
    return blob[offset:end].decode("ascii", "replace")


class PEFile:
    """Just enough PE parsing to read the import and delay-import tables."""

    def __init__(self, blob: bytes):
        self.blob = blob
        if blob[:2] != b"MZ":
            raise PEError("not a PE image (no MZ)")
        pe_off = struct.unpack_from("<I", blob, 0x3C)[0]
        if blob[pe_off:pe_off + 4] != b"PE\0\0":
            raise PEError("not a PE image (no PE signature)")

        coff = pe_off + 4
        n_sections, = struct.unpack_from("<H", blob, coff + 2)
        opt_size, = struct.unpack_from("<H", blob, coff + 16)
        opt = coff + 20

        magic, = struct.unpack_from("<H", blob, opt)
        if magic == 0x10B:      # PE32
            dir_count_off = opt + 92
        elif magic == 0x20B:    # PE32+
            dir_count_off = opt + 108
        else:
            raise PEError(f"unknown optional header magic 0x{magic:x}")

        n_dirs, = struct.unpack_from("<I", blob, dir_count_off)
        dirs_off = dir_count_off + 4
        self.data_dirs = [
            struct.unpack_from("<II", blob, dirs_off + 8 * i)
            for i in range(n_dirs)
        ]

        sect_off = opt + opt_size
        self.sections = []
        for i in range(n_sections):
            base = sect_off + 40 * i
            virt_size, virt_addr, raw_size, raw_ptr = struct.unpack_from(
                "<IIII", blob, base + 8)
            self.sections.append((virt_addr, max(virt_size, raw_size),
                                  raw_size, raw_ptr))

    def offset(self, rva: int) -> int | None:
        for virt_addr, span, raw_size, raw_ptr in self.sections:
            if virt_addr <= rva < virt_addr + span:
                delta = rva - virt_addr
                if delta >= raw_size:
                    return None  # lives in uninitialised data
                return raw_ptr + delta
        return None

    def _dir(self, index: int) -> tuple[int, int]:
        if index >= len(self.data_dirs):
            return (0, 0)
        return self.data_dirs[index]

    def imports(self) -> list[str]:
        rva, size = self._dir(1)
        if not rva or not size:
            return []
        start = self.offset(rva)
        if start is None:
            return []
        names = []
        for i in range(4096):
            entry = start + 20 * i
            if entry + 20 > len(self.blob):
                break
            fields = struct.unpack_from("<IIIII", self.blob, entry)
            if not any(fields):
                break
            name_off = self.offset(fields[3])
            if name_off is not None:
                names.append(_cstr(self.blob, name_off))
        return names

    def delay_imports(self) -> list[str]:
        rva, size = self._dir(13)
        if not rva or not size:
            return []
        start = self.offset(rva)
        if start is None:
            return []
        names = []
        for i in range(4096):
            entry = start + 32 * i
            if entry + 32 > len(self.blob):
                break
            fields = struct.unpack_from("<IIIIIIII", self.blob, entry)
            if not any(fields):
                break
            attrs, name_rva = fields[0], fields[1]
            # Bit 0 of Attributes means the descriptor uses RVAs. Old linkers
            # wrote absolute VAs instead; those we cannot resolve without the
            # image base, so skip rather than guess.
            if not attrs & 1:
                continue
            name_off = self.offset(name_rva)
            if name_off is not None:
                names.append(_cstr(self.blob, name_off))
        return names


def is_system(name: str) -> bool:
    low = name.lower()
    return low in SYSTEM_DLLS or low.startswith(SYSTEM_PREFIXES)


def audit_imports(root: Path, extra_allowed: set[str]) -> tuple[int, int]:
    binaries = sorted(
        p for p in root.rglob("*")
        if p.is_file() and p.suffix.lower() in (".dll", ".exe", ".pyd", ".drv")
    )
    if not binaries:
        print(f"::error::no PE binaries found under {root} — wrong path?")
        return (1, 0)

    present = {p.name.lower() for p in binaries}
    missing: dict[str, set[str]] = {}
    missing_delay: dict[str, set[str]] = {}
    unreadable = []

    for path in binaries:
        try:
            pe = PEFile(path.read_bytes())
            hard, delayed = pe.imports(), pe.delay_imports()
        except (PEError, struct.error, OSError) as exc:
            unreadable.append(f"{path.relative_to(root)}: {exc}")
            continue
        rel = path.relative_to(root).as_posix()
        for dep in hard:
            low = dep.lower()
            if low not in present and not is_system(dep) and low not in extra_allowed:
                missing.setdefault(dep, set()).add(rel)
        for dep in delayed:
            low = dep.lower()
            if low not in present and not is_system(dep) and low not in extra_allowed:
                missing_delay.setdefault(dep, set()).add(rel)

    print(f"Scanned {len(binaries)} PE binaries under {root}")
    if unreadable:
        print(f"  {len(unreadable)} file(s) could not be parsed:")
        for line in unreadable[:10]:
            print(f"    {line}")

    if missing_delay:
        print("")
        print("Delay-loaded imports not present in the package "
              "(tolerated — these fail only when the feature is used):")
        for dep in sorted(missing_delay):
            importers = ", ".join(sorted(missing_delay[dep])[:4])
            print(f"  {dep}  <- {importers}")

    if not missing:
        print("")
        print("OK: every hard-linked import resolves inside the package or to a system DLL.")
        return (0, len(binaries))

    print("")
    for dep in sorted(missing):
        importers = sorted(missing[dep])
        shown = ", ".join(importers[:6])
        if len(importers) > 6:
            shown += f", … (+{len(importers) - 6} more)"
        print(f"::error::missing runtime dependency: {dep} — imported by {shown}")
    print("")
    print(f"{len(missing)} DLL(s) are imported but not shipped. Whatever "
          "imports one cannot load without it: fatal at startup when the "
          "importer is fontmatrix.exe or something it links, a silently dead "
          "feature when it is a plugin loaded on demand. Either add the "
          "providing Craft package to setDependencies() in "
          "craft-blueprints/fontmatrix/fontmatrix.py and stop excluding it in "
          "ignoredPackages, or \u2014 when the importer is something we "
          "deliberately do not use \u2014 drop that file in blacklist.txt.")
    print("")
    print("Note when writing a blacklist pattern: the paths above are from "
          "the finished package, but blacklist.txt is matched earlier, while "
          "files are copied out of each package's image dir. Anything under "
          "bin/ that is really a plugin lives at plugins/<...> at that point "
          "\u2014 bin/kf6/x.dll has to be matched as plugins/kf6/x.dll.")
    return (1, len(binaries))


def audit_payload(root: Path) -> int:
    failures = 0
    print("")
    print("Checking runtime data files:")
    for pattern, why in EXPECTED_PAYLOAD:
        matches = list(root.glob(pattern))
        if matches:
            extra = f" ({len(matches)} files)" if len(matches) > 1 else ""
            print(f"  ok      {pattern}{extra}")
        else:
            failures += 1
            print(f"::error::missing from package: {pattern} — needed for {why}")
    if failures:
        print("")
        print(f"{failures} expected path(s) are absent. These are installed by "
              "CMake, so check that the install rule is not inside a "
              "platform branch that skips Windows.")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", type=Path, help="staged package root")
    parser.add_argument("--allow", action="append", default=[], metavar="DLL",
                        help="treat this DLL as externally provided")
    parser.add_argument("--no-payload", action="store_true",
                        help="only audit PE imports, skip the data-file check")
    args = parser.parse_args()

    root = args.root
    if not root.is_dir():
        print(f"::error::{root} is not a directory")
        return 1

    rc, _ = audit_imports(root, {d.lower() for d in args.allow})
    if not args.no_payload:
        rc |= audit_payload(root)
    return rc


if __name__ == "__main__":
    sys.exit(main())
